// components/SDK/uploader-sdk.tsx
'use client'

import { useState, useRef } from 'react'

export interface DriveUploaderProps {
  /** The resumable upload URL generated by your server */
  uploadUrl: string
  /** Callback for upload progress (0-100) */
  onProgress?: (progress: number) => void
  /** Callback for successful upload */
  onSuccess?: () => void
  /** Callback for failed upload */
  onError?: (error: string) => void
  /** Custom labeling for the button */
  label?: string
  /** Custom CSS classes for the container */
  className?: string
  /** Custom CSS classes for the button */
  buttonClassName?: string
  /** Maximum file size in bytes */
  maxSize?: number
}

/**
 * Drive Wrapper SDK: A lightweight component for direct-to-cloud uploads.
 * Use this in your frontend after requesting a session URL from your backend.
 */
export function DriveUploaderSDK({
  uploadUrl,
  onProgress,
  onSuccess,
  onError,
  label = 'Upload to Drive',
  className = '',
  buttonClassName = '',
  maxSize
}: DriveUploaderProps) {
  const [isUploading, setIsUploading] = useState(false)
  const [progress, setProgress] = useState(0)
  const fileInputRef = useRef<HTMLInputElement>(null)

  const handleUpload = async (file: File) => {
    if (maxSize && file.size > maxSize) {
      onError?.(`File too large. Max size is ${Math.round(maxSize / 1024 / 1024)}MB`)
      return
    }

    if (!uploadUrl) {
      onError?.('Missing upload URL')
      return
    }

    setIsUploading(true)
    setProgress(0)

    try {
      await new Promise((resolve, reject) => {
        const xhr = new XMLHttpRequest()
        let currentProgress = 0
        
        xhr.open('PUT', uploadUrl)
        
        xhr.upload.onprogress = (event) => {
          if (event.lengthComputable) {
            currentProgress = Math.round((event.loaded / event.total) * 100)
            setProgress(currentProgress)
            onProgress?.(currentProgress)
          }
        }

        xhr.onload = () => {
          if (xhr.status >= 200 && xhr.status < 300) {
            resolve(xhr.response)
          } else {
            reject(new Error(`Upload failed with status ${xhr.status}`))
          }
        }

        xhr.onerror = () => {
          // Handle Google's sporadic CORS response behavior on success
          if (currentProgress >= 100) {
            resolve('Assuming success')
          } else {
            reject(new Error('Network error or CORS issue'))
          }
        }

        xhr.send(file)
      })

      setIsUploading(false)
      setProgress(100)
      onSuccess?.()
    } catch (err: any) {
      setIsUploading(false)
      onError?.(err.message || 'Upload failed')
    }
  }

  const onFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files?.[0]) {
      handleUpload(e.target.files[0])
    }
  }

  return (
    <div className={`drive-wrapper-sdk ${className}`}>
      <input
        type="file"
        ref={fileInputRef}
        onChange={onFileChange}
        className="hidden"
        disabled={isUploading}
      />
      
      <button
        onClick={() => fileInputRef.current?.click()}
        disabled={isUploading}
        className={`px-4 py-2 rounded-lg font-medium transition-all active:scale-95 disabled:opacity-50 disabled:active:scale-100 ${
          buttonClassName || 'bg-blue-600 text-white hover:bg-blue-700'
        }`}
      >
        {isUploading ? `Uploading... ${progress}%` : label}
      </button>

      {isUploading && (
        <div className="w-full mt-2 bg-zinc-100 rounded-full h-1.5 overflow-hidden">
          <div 
            className="bg-blue-600 h-full transition-all duration-300"
            style={{ width: `${progress}%` }}
          />
        </div>
      )}
    </div>
  )
}
